language: node_js
node_js:
- v6
- v5
- v4
before_script:
- npm install -g gulp
script: gulp
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: npm
  email: paolo.chiabrera@gmail.com
  api_key:
    secure: epREBnd0OHvPr79eGfJGdDzi+5p/ErkshdIuJ0cVxEwzIir2AC7qzsOZdq3BE8EiRIJnAbgQslbv5VJvYA1HDUrmo3SSllY6O7B16cXnUt5hQd8I64cUhnDY9MRfJVSGDlzZDYlLxbEYGwNZ+tS7kjFd4VcVQqlgRJamlQORi+AAbWFwbaUqkKgxvYuh7dp1l5jrixJ9Osp3PofRPrB52w6ZFa4Fpj/Y6p6MMS1Dmj+5kjPxZAvxE4hJ9sZaI06+MfLGkS/cPn8N5yGiWQRjwSY/KJPbCm0RBE+ECp0zOvjbrQeKwfUFIxVebMwPNA0xYNVwCf5YfQJ2K+QOgBEF0sqGzNtFdAvuDk78ozWreQsF3QF5/gYJQhVu27UWGaVMfP4gTfaXLYfScKUgqOVwmeeir89HoVXXLMpb2zEOYh5Y4XUQ5tdf7rLZIStPugcIBb50Bv6VlOSvc/ZioZBTj5S3f9ot5+mSyw08gcWAmMO5bX9xuiBY9U/hskEFjwrpUF9d/b3JoB7DWo7gMN+t/87zZ8aLEGRISOFipdgqqVi/Dh/ZxdM0eJXcXN6CB4Tb0ibL8zY9/PC94Xla4SZ6wN/HNrb30LEk5YfCqEPglpqWybvLhZ4F/80uOjyJYfnqZJDOzFDgMKxYQViUP/OiIDD3VNo5tWmUaGYDz9DkCCM=
  on:
    tags: true
    node: v6
    repo: paolo-chiabrera/pmp-scheduler
